name: CI - Rails Tests, Lint, and JS Scan

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Bundler dependencies
        uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-bundler-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-bundler-

      - name: Build Test Image
        run: |
          docker build -f Dockerfile.test -t rails-test .

      - name: Run RSpec Tests
        run: |
          docker run --rm \
            -v "$(pwd)":/app \
            rails-test rspec spec

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install RuboCop
        run: |
          gem install rubocop
          rubocop --version

      - name: Run RuboCop
        run: |
          rubocop

  scan_js:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Dependencies
        run: |
          npm install

      - name: Run scan_js
        run: |
          npm run scan_js
